#!/usr/bin/env python3

import subprocess
import argparse

parser = argparse.ArgumentParser(
    prog= 'lvman',
    description='Start or stop libvirt-bin and virtlogd.')
parser.add_argument('--start', help='starts libvirt-bin and virtlogd', action='store_true')
parser.add_argument('--stop', help='stops libvirt-bin and virtlogd', action='store_true')

args = parser.parse_args()

start = vars(args)['start']
stop = vars(args)['stop']

if start:
    print('libvirt-bin and virtlogd started')
    subprocess.run(["systemctl", "start", "virtlogd"])
    subprocess.run(["systemctl", "start", "libvirt-bin"])
elif stop:
    print('libvirt-bin and virtlogd stopped')
    subprocess.run(["systemctl", "stop", "libvirt-bin"])
    subprocess.run(["systemctl", "stop", "virtlogd"])
else:
    print('unrecognised command')
